title: HeadMouse Pi
baseurl: "/HeadMouse-Pi"
url: "https://doudulac.github.io"
github_username:  doudulac
show_downloads: true
timezone: America/New_York

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
